import re

_LANGUAGE_ALIASES: dict[str, str] = {
    "jl": "julia",
    "py": "python",
    "python3": "python",
    "c++": "cpp",
    "cxx": "cpp",
    "cc": "cpp",
    "cu": "cuda",
    "golang": "go",
    "md": "markdown",
    "f90": "fortran",
    "f95": "fortran",
    "f03": "fortran",
    "f08": "fortran",
    "wl": "wolfram",
    "wls": "wolfram",
    "mathematica": "wolfram",
    "sv": "verilog",
    "sverilog": "verilog",
    "systemverilog": "verilog",
}

_LANGUAGE_EXTENSIONS: dict[str, str] = {
    "cuda": "cu",
    "cpp": "cpp",
    "go": "go",
    "python": "py",
    "rust": "rs",
    "swift": "swift",
    "json": "json",
    "json5": "json",
    "julia": "jl",
    "markdown": "md",
    "fortran": "f90",
    "wolfram": "wl",
    "verilog": "sv",
}

_EVOLVE_COMMENT_PREFIXES: dict[str, str] = {
    "cuda": "//",
    "cpp": "//",
    "go": "//",
    "python": "#",
    "rust": "//",
    "swift": "//",
    "json": "//",
    "json5": "//",
    "julia": "#",
    "markdown": "<!--",
    "fortran": "!",
    "wolfram": "(*",
    "verilog": "//",
}

_LANGUAGE_FENCE_TAGS: dict[str, tuple[str, ...]] = {
    "cuda": ("cuda", "cu"),
    "cpp": ("cpp", "c++", "cc", "cxx"),
    "go": ("go", "golang"),
    "python": ("python", "py"),
    "rust": ("rust", "rs"),
    "swift": ("swift",),
    "json": ("json",),
    "json5": ("json5", "json"),
    "julia": ("julia", "jl"),
    "markdown": ("markdown", "md"),
    "fortran": ("fortran", "f90", "f95", "f03", "f08"),
    "wolfram": ("wolfram", "mathematica", "wl", "wls"),
    "verilog": ("verilog", "systemverilog", "sv"),
}


def normalize_language(language: str) -> str:
    normalized = language.strip().lower()
    canonical = _LANGUAGE_ALIASES.get(normalized, normalized)
    if canonical not in _LANGUAGE_EXTENSIONS:
        raise ValueError(f"Language {language} not supported")
    return canonical


def get_language_extension(language: str) -> str:
    return _LANGUAGE_EXTENSIONS[normalize_language(language)]


def get_evolve_comment_prefix(language: str) -> str:
    return _EVOLVE_COMMENT_PREFIXES[normalize_language(language)]


def get_code_fence_languages(language: str) -> tuple[str, ...]:
    canonical = normalize_language(language)
    requested_tag = language.strip().lower()
    ordered_tags = [requested_tag]
    for tag in _LANGUAGE_FENCE_TAGS[canonical]:
        if tag not in ordered_tags:
            ordered_tags.append(tag)
    return tuple(ordered_tags)


# ---------------------------------------------------------------------------
# EVOLVE-BLOCK marker patterns
#
# Each language defines:
#   - A regex that a *correctly-formed* marker line must match end-to-end.
#     The line must consist of the marker only, properly comment-wrapped for
#     the language. This is the canonical form generated by ShinkaEvolve and
#     the form we require LLM output to use.
#   - A canonical example string for use in error messages.
#
# The motivation for being strict here is the failure mode observed with
# Wolfram, where the LLM occasionally emitted both markers inside a *single*
# (* ... *) comment block:
#
#     (* EVOLVE-BLOCK-START
#     solve[] := ...
#      EVOLVE-BLOCK-END *)
#
# The patch applier accepted that file because the literal marker strings
# were present, but the entire candidate code body was actually inside one
# big comment, so solve[] was never defined and the candidate silently
# failed validation. The validator below catches this.
# ---------------------------------------------------------------------------

_EVOLVE_MARKER_PATTERNS: dict[str, tuple[re.Pattern, re.Pattern]] = {
    "python": (
        re.compile(r"^\s*#\s*EVOLVE-BLOCK-START\s*$"),
        re.compile(r"^\s*#\s*EVOLVE-BLOCK-END\s*$"),
    ),
    "julia": (
        re.compile(r"^\s*#\s*EVOLVE-BLOCK-START\s*$"),
        re.compile(r"^\s*#\s*EVOLVE-BLOCK-END\s*$"),
    ),
    "cpp": (
        re.compile(r"^\s*//\s*EVOLVE-BLOCK-START\s*$"),
        re.compile(r"^\s*//\s*EVOLVE-BLOCK-END\s*$"),
    ),
    "go": (
        re.compile(r"^\s*//\s*EVOLVE-BLOCK-START\s*$"),
        re.compile(r"^\s*//\s*EVOLVE-BLOCK-END\s*$"),
    ),
    "cuda": (
        re.compile(r"^\s*//\s*EVOLVE-BLOCK-START\s*$"),
        re.compile(r"^\s*//\s*EVOLVE-BLOCK-END\s*$"),
    ),
    "rust": (
        re.compile(r"^\s*//\s*EVOLVE-BLOCK-START\s*$"),
        re.compile(r"^\s*//\s*EVOLVE-BLOCK-END\s*$"),
    ),
    "swift": (
        re.compile(r"^\s*//\s*EVOLVE-BLOCK-START\s*$"),
        re.compile(r"^\s*//\s*EVOLVE-BLOCK-END\s*$"),
    ),
    "json": (
        re.compile(r"^\s*//\s*EVOLVE-BLOCK-START\s*$"),
        re.compile(r"^\s*//\s*EVOLVE-BLOCK-END\s*$"),
    ),
    "json5": (
        re.compile(r"^\s*//\s*EVOLVE-BLOCK-START\s*$"),
        re.compile(r"^\s*//\s*EVOLVE-BLOCK-END\s*$"),
    ),
    "fortran": (
        re.compile(r"^\s*!\s*EVOLVE-BLOCK-START\s*$"),
        re.compile(r"^\s*!\s*EVOLVE-BLOCK-END\s*$"),
    ),
    "markdown": (
        re.compile(r"^\s*<!--\s*EVOLVE-BLOCK-START\s*-->\s*$"),
        re.compile(r"^\s*<!--\s*EVOLVE-BLOCK-END\s*-->\s*$"),
    ),
    "wolfram": (
        re.compile(r"^\s*\(\*\s*EVOLVE-BLOCK-START\s*\*\)\s*$"),
        re.compile(r"^\s*\(\*\s*EVOLVE-BLOCK-END\s*\*\)\s*$"),
    ),
    "verilog": (
        re.compile(r"^\s*//\s*EVOLVE-BLOCK-START\s*$"),
        re.compile(r"^\s*//\s*EVOLVE-BLOCK-END\s*$"),
    ),
}

_EVOLVE_MARKER_EXAMPLES: dict[str, tuple[str, str]] = {
    "python": ("# EVOLVE-BLOCK-START", "# EVOLVE-BLOCK-END"),
    "julia": ("# EVOLVE-BLOCK-START", "# EVOLVE-BLOCK-END"),
    "cpp": ("// EVOLVE-BLOCK-START", "// EVOLVE-BLOCK-END"),
    "go": ("// EVOLVE-BLOCK-START", "// EVOLVE-BLOCK-END"),
    "cuda": ("// EVOLVE-BLOCK-START", "// EVOLVE-BLOCK-END"),
    "rust": ("// EVOLVE-BLOCK-START", "// EVOLVE-BLOCK-END"),
    "swift": ("// EVOLVE-BLOCK-START", "// EVOLVE-BLOCK-END"),
    "json": ("// EVOLVE-BLOCK-START", "// EVOLVE-BLOCK-END"),
    "json5": ("// EVOLVE-BLOCK-START", "// EVOLVE-BLOCK-END"),
    "fortran": ("! EVOLVE-BLOCK-START", "! EVOLVE-BLOCK-END"),
    "markdown": ("<!-- EVOLVE-BLOCK-START -->", "<!-- EVOLVE-BLOCK-END -->"),
    "wolfram": ("(* EVOLVE-BLOCK-START *)", "(* EVOLVE-BLOCK-END *)"),
    "verilog": ("// EVOLVE-BLOCK-START", "// EVOLVE-BLOCK-END"),
}

# Languages whose comments span multiple lines. For these, marker validation
# additionally checks that the file's comment delimiters are *globally
# balanced* — see marker_validation.py.
_BLOCK_COMMENT_LANGUAGES: frozenset[str] = frozenset({"wolfram", "markdown"})

_BLOCK_COMMENT_DELIMS: dict[str, tuple[str, str]] = {
    "wolfram": ("(*", "*)"),
    "markdown": ("<!--", "-->"),
}


def get_evolve_marker_patterns(language: str) -> tuple[re.Pattern, re.Pattern]:
    """Return (start_regex, end_regex) for fully-formed EVOLVE-BLOCK markers."""
    canonical = normalize_language(language)
    if canonical not in _EVOLVE_MARKER_PATTERNS:
        raise ValueError(f"No EVOLVE-BLOCK marker patterns defined for {language!r}")
    return _EVOLVE_MARKER_PATTERNS[canonical]


def get_evolve_marker_examples(language: str) -> tuple[str, str]:
    """Return canonical (start, end) marker example strings for the language."""
    canonical = normalize_language(language)
    if canonical not in _EVOLVE_MARKER_EXAMPLES:
        raise ValueError(f"No EVOLVE-BLOCK marker examples defined for {language!r}")
    return _EVOLVE_MARKER_EXAMPLES[canonical]


def has_block_comments(language: str) -> bool:
    """Whether the language's comment syntax can span multiple lines."""
    return normalize_language(language) in _BLOCK_COMMENT_LANGUAGES


def get_block_comment_delims(language: str) -> tuple[str, str]:
    """Return (open, close) block-comment delimiters; raises if language uses
    line comments only."""
    canonical = normalize_language(language)
    if canonical not in _BLOCK_COMMENT_DELIMS:
        raise ValueError(f"{language!r} does not have block comments")
    return _BLOCK_COMMENT_DELIMS[canonical]
