max_evaluation_jobs: 1
max_proposal_jobs: 2
max_db_workers: 2

evo_config:
  _target_: shinka.core.EvolutionConfig
  patch_types:
    - "diff"
    - "full"
  patch_type_probs:
    - 0.5
    - 0.5
  num_generations: 20
  max_patch_attempts: 10
  llm_models:
    - "gpt-4.1"
  llm_dynamic_selection: null
  embedding_model: "text-embedding-3-small"
  enable_controlled_oversubscription: false
  results_dir: ${output_dir}
